2024-10-17 15:49:04,150 - INFO - Starting the automator-controller
2024-10-17 15:49:04,150 - INFO - Executing ~/automator-lnd/scripts/get_channels_data.py
2024-10-17 15:49:04,151 - INFO - Executing ~/automator-lnd/scripts/auto-rebalancer-config.py
2024-10-17 15:49:04,169 - ERROR - Error executing ~/automator-lnd/scripts/auto-rebalancer-config.py: Command '['python3', '~/automator-lnd/scripts/auto-rebalancer-config.py']' returned non-zero exit status 2.
2024-10-17 15:49:04,169 - ERROR - Error executing ~/automator-lnd/scripts/get_channels_data.py or ~/automator-lnd/scripts/autofee.py: Command '['python3', '~/automator-lnd/scripts/get_channels_data.py']' returned non-zero exit status 2.
2024-10-17 15:49:08,354 - INFO - Automator-controller manually interrupted.
2024-10-17 15:49:08,354 - INFO - Automator-controller finished.
2024-10-17 15:49:35,000 - INFO - Starting the automator-controller
2024-10-17 15:49:35,000 - INFO - Executing /automator-lnd/scripts/get_channels_data.py
2024-10-17 15:49:35,000 - INFO - Executing /automator-lnd/scripts/auto-rebalancer-config.py
2024-10-17 15:49:35,018 - ERROR - Error executing /automator-lnd/scripts/get_channels_data.py or /automator-lnd/scripts/autofee.py: Command '['python3', '/automator-lnd/scripts/get_channels_data.py']' returned non-zero exit status 2.
2024-10-17 15:49:35,019 - ERROR - Error executing /automator-lnd/scripts/auto-rebalancer-config.py: Command '['python3', '/automator-lnd/scripts/auto-rebalancer-config.py']' returned non-zero exit status 2.
2024-10-17 15:49:37,986 - INFO - Automator-controller manually interrupted.
2024-10-17 15:49:37,987 - INFO - Automator-controller finished.
